### ISSUE TITLE
could not resolve [models/dense_vnet_abdominal_ct]

### ISSUE THREAD

**Issue by baibaidj** [NifTK/NiftyNetModelZoo#4]
Hi. 
I tried to run the example code of dense_vnet_abdominal_ct, and tried really hard to debug but failed. 
The error that I came across is as the following pic. 
![selection_030](https://user-images.githubusercontent.com/24452296/45672968-16e08b80-bb5c-11e8-9aea-85876bc83ee7.png)

My system is ubuntu 16.04 and I cloned the NiftyNet to my local disk and unzip the three files under the niftynet folder as follows. 
![selection_031](https://user-images.githubusercontent.com/24452296/45673270-d2a1bb00-bb5c-11e8-86dd-09337f793942.png)

If this is not a proper place to post this problem, please let me know and I will go to stackflow. 

Thank you so much.

**Comment by wyli** [comment]
Hi @baibaidj, I think you're almost there, adding the path `/media/dejun/holder/NiftyNet-dev/niftynet` to `$PYTHONPATH` should work.

This is not a proper place to post this type of question, next time please go to stackoverflow; also it would be great if you post texts instead of images so that the question is searchable and helpful for others as well.
